sh fapkc.sh baidu
sh fapkc.sh huawei
#sh fapkc.sh Lenovo
#sh fapkc.sh oppo
#sh fapkc.sh qihu
#sh fapkc.sh vivo
#sh fapkc.sh xiaomi
#sh fapkc.sh yingyongbao
#sh fapkc.sh samsung
#sh fapkc.sh sougou
#sh fapkc.sh meizu
